apiVersion: v1
kind: ConfigMap
metadata:
  name: squidex
data:
  MONGODB__CONFIGURATION: {{ .Values.mongoconnectionstring}}
  DOMAIN: https://{{ .Values.domain }}
  ADMIN_EMAIL: {{ .Values.adminEmail }}
  S3_BUCKET: {{ .Values.S3Bucket }}
  CONTENTS__USETRANSACTIONS: "{{ .Values.useTransactions }}"
  FULLTEXT__ELASTIC__OPENSEARCH: "true"