adminEmail: squidex-staging-45@homerlearning.com
S3Bucket: homer-squidex-staging
useTransactions: false
secretName: "staging-v2-squidex"
loggingLevel: warning
ingressEnabled: true
domain: squidex-staging-v2.learnwithhomer.com