adminEmail: web-cms-v1@homerlearning.com
S3Bucket: homer-squidex-web-cms
secretName: web-cms-squidex
useTransactions: false
loggingLevel: warning
replicas: 2
ingressEnabled: true
domain: squidex-web-cms.learnwithhomer.com